/**
 * NOTE: Test has beeen generated by ChatGpt
 * This test cover a lot of methods in the NehonixUriProcessor class
 * Test suite for NehonixURIProcessor
 * This file contains various test cases for different encoding types and scenarios.
 */

import { NehonixURIProcessor } from "..";
// const enc = NehonixURIProcessor.encode(
//   "Hello world I'm Eleazar !",
//   "quotedPrintable"
// );
// console.log("encoded res: ", enc);

const NES = NehonixURIProcessor;

// Real-world application: Encoding user input for various contexts
function secureUserInput(input: string, context: string) {
  switch (context) {
    case "url":
      return NES.encode(input, "percentEncoding");
    case "urlParam":
      return NES.encode(input, "urlSafeBase64");
    case "html":
      return NES.encode(input, "htmlEntity");
    case "js":
      return NES.encode(input, "jsEscape");
    case "css":
      return NES.encode(input, "cssEscape");
    case "email":
      return NES.encode(input, "quotedPrintable");
    case "obfuscate":
      return NES.encode(input, "rot13");
    default:
      return input;
  }
}

// Example usage of the secureUserInput function
const userInput = "<img src=x onerror=alert(1)>";
console.log("Secured for JS:", secureUserInput(userInput, "js"));
console.log("Secured for HTML:", secureUserInput(userInput, "html"));
